services:
  mysql:
    image: mysql:8.0
    container_name: mysql-notifica
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notifica
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s

  backend:
    build: .
    container_name: notifica-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/notifica
    depends_on:
      mysql:
        condition: service_healthy
    restart: on-failure

  frontend:
    build:
      context: C:/Users/fabio/Documents/Notifica-FrontEnd/Notifica-FrontEnd
      dockerfile: Dockerfile
    container_name: notifica-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  mysql-data: